sudo: false

language:
  - python

python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
  - 3.7

install:
  - pip install pytest pytest-cov python-coveralls

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then py.test -vv prog.py --cov prog;
    else py.test -vv prog.py;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then coveralls;
    fi

notifications:
  email: false

